/**
 * Created by chao on 2017/10/23.
 */

export const SETHOMEDATA = 'SETHOMEDATA';
export const SETTOPICDATA = 'SETTOPICDATA';
export const SETGAMEDETAILSDATA = 'SETGAMEDETAILSDATA';
export const SETUSERDATA = 'SETUSERDATA';
export const LOGIN = 'LOGIN';
export const LOGINOUT = 'LOGINOUT';
export const SERVICELISTDATA = 'SERVICELISTDATA';
export const GETMYSERVICELIS = 'GETMYSERVICELIS';
export const GETTIMELENGTH = 'GETTIMELENGTH';
export const GETEXTRAID = 'GETEXTRAID';
